### ISSUE TITLE
Spending from coinbase error

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/ocean-wallet#108]
When creating a new transaction spending coinbase outputs:

Traceback (most recent call last):
  File "/Users/ttrevethan/cb-client-wallet/electrum/gui/qt/main_window.py", line 1615, in make_transaction_and_send
    is_sweep=is_sweep, b_allow_zerospend=b_allow_zerospend)
  File "/Users/ttrevethan/cb-client-wallet/electrum/wallet.py", line 608, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), b_allow_zerospend)
  File "/Users/ttrevethan/cb-client-wallet/electrum/coinchooser.py", line 236, in make_tx
    buckets = self.bucketize_coins(coins)
  File "/Users/ttrevethan/cb-client-wallet/electrum/coinchooser.py", line 111, in bucketize_coins
    return list(map(make_Bucket, buckets.keys(), buckets.values()))
  File "/Users/ttrevethan/cb-client-wallet/electrum/coinchooser.py", line 106, in make_Bucket
    for coin in coins)
  File "/Users/ttrevethan/cb-client-wallet/electrum/coinchooser.py", line 106, in <genexpr>
    for coin in coins)
  File "/Users/ttrevethan/cb-client-wallet/electrum/transaction.py", line 1206, in estimated_input_weight
    witness_size = len(cls.serialize_witness_in(txin, True)) // 2
  File "/Users/ttrevethan/cb-client-wallet/electrum/transaction.py", line 883, in serialize_witness_in
    s = var_int(len(txin['issuance_range_proof']))
KeyError: 'issuance_range_proof'

Seems to be trying to look at the (non-existent) inputs.

**Comment by tomt1664** [comment]
This was due to trying to spend from a multisig watch only wallet with no xpubs, so there was no redeem script.
